// <auto-generated />
using FirstMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstMVC.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20240308073025_Create_table_Customer")]
    partial class Create_table_Customer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("FirstMVC.Models.Customer", b =>
                {
                    b.Property<string>("CusstomerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.HasKey("CusstomerID");

                    b.ToTable("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
